// <auto-generated />
using System;
using FleetMaintenanceApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FleetMaintenanceApi.Migrations
{
    [DbContext(typeof(FleetMaintenanceDbContext))]
    [Migration("20260613091440_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FleetMaintenanceApi.Models.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("DriverId");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            DriverId = 1,
                            City = "Coimbatore",
                            DriverName = "Ramesh Kumar",
                            IsAvailable = true,
                            LicenseNumber = "DL2026TN1001",
                            PhoneNumber = "9876543210"
                        },
                        new
                        {
                            DriverId = 2,
                            City = "Chennai",
                            DriverName = "Suresh Babu",
                            IsAvailable = true,
                            LicenseNumber = "DL2025TN1002",
                            PhoneNumber = "9876543211"
                        },
                        new
                        {
                            DriverId = 3,
                            City = "Madurai",
                            DriverName = "Arjun Patel",
                            IsAvailable = false,
                            LicenseNumber = "DL2024TN1003",
                            PhoneNumber = "9876543212"
                        },
                        new
                        {
                            DriverId = 4,
                            City = "Salem",
                            DriverName = "Karthik Rajan",
                            IsAvailable = true,
                            LicenseNumber = "DL2023TN1004",
                            PhoneNumber = "9876543213"
                        },
                        new
                        {
                            DriverId = 5,
                            City = "Trichy",
                            DriverName = "Vijay Murugan",
                            IsAvailable = true,
                            LicenseNumber = "DL2022TN1005",
                            PhoneNumber = "9876543214"
                        },
                        new
                        {
                            DriverId = 6,
                            City = "Erode",
                            DriverName = "Dinesh Selvam",
                            IsAvailable = true,
                            LicenseNumber = "DL2021TN1006",
                            PhoneNumber = "9876543215"
                        },
                        new
                        {
                            DriverId = 7,
                            City = "Vellore",
                            DriverName = "Pradeep Nair",
                            IsAvailable = false,
                            LicenseNumber = "DL2020TN1007",
                            PhoneNumber = "9876543216"
                        },
                        new
                        {
                            DriverId = 8,
                            City = "Tirunelveli",
                            DriverName = "Manoj Krishnan",
                            IsAvailable = true,
                            LicenseNumber = "DL2019TN1008",
                            PhoneNumber = "9876543217"
                        },
                        new
                        {
                            DriverId = 9,
                            City = "Coimbatore",
                            DriverName = "Ravi Shankar",
                            IsAvailable = true,
                            LicenseNumber = "DL2026TN1009",
                            PhoneNumber = "9876543218"
                        },
                        new
                        {
                            DriverId = 10,
                            City = "Chennai",
                            DriverName = "Balaji Natarajan",
                            IsAvailable = true,
                            LicenseNumber = "DL2025TN1010",
                            PhoneNumber = "9876543219"
                        });
                });

            modelBuilder.Entity("FleetMaintenanceApi.Models.MaintenanceRecord", b =>
                {
                    b.Property<int>("MaintenanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaintenanceId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("ServiceCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("date");

                    b.Property<string>("ServiceStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("MaintenanceId");

                    b.HasIndex("DriverId");

                    b.HasIndex("VehicleId");

                    b.ToTable("MaintenanceRecords");

                    b.HasData(
                        new
                        {
                            MaintenanceId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 1,
                            Remarks = "Regular oil replacement",
                            ServiceCost = 2500.00m,
                            ServiceDate = new DateOnly(2026, 1, 5),
                            ServiceStatus = "Completed",
                            ServiceType = "Oil Change",
                            VehicleId = 1
                        },
                        new
                        {
                            MaintenanceId = 2,
                            CreatedDate = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 2,
                            Remarks = "Brake pads replaced",
                            ServiceCost = 1800.00m,
                            ServiceDate = new DateOnly(2026, 1, 10),
                            ServiceStatus = "Completed",
                            ServiceType = "Brake Inspection",
                            VehicleId = 2
                        },
                        new
                        {
                            MaintenanceId = 3,
                            CreatedDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 3,
                            Remarks = "Engine oil leak fixed",
                            ServiceCost = 15000.00m,
                            ServiceDate = new DateOnly(2026, 1, 15),
                            ServiceStatus = "Completed",
                            ServiceType = "Engine Repair",
                            VehicleId = 3
                        },
                        new
                        {
                            MaintenanceId = 4,
                            CreatedDate = new DateTime(2026, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 4,
                            Remarks = "All four tyres replaced",
                            ServiceCost = 8000.00m,
                            ServiceDate = new DateOnly(2026, 2, 3),
                            ServiceStatus = "Completed",
                            ServiceType = "Tyre Replacement",
                            VehicleId = 4
                        },
                        new
                        {
                            MaintenanceId = 5,
                            CreatedDate = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 5,
                            Remarks = "Battery terminals cleaned",
                            ServiceCost = 500.00m,
                            ServiceDate = new DateOnly(2026, 2, 8),
                            ServiceStatus = "Completed",
                            ServiceType = "Battery Check",
                            VehicleId = 5
                        },
                        new
                        {
                            MaintenanceId = 6,
                            CreatedDate = new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 6,
                            Remarks = "Full general service done",
                            ServiceCost = 3500.00m,
                            ServiceDate = new DateOnly(2026, 2, 12),
                            ServiceStatus = "Completed",
                            ServiceType = "General Service",
                            VehicleId = 6
                        },
                        new
                        {
                            MaintenanceId = 7,
                            CreatedDate = new DateTime(2026, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 7,
                            Remarks = "Synthetic oil used",
                            ServiceCost = 2800.00m,
                            ServiceDate = new DateOnly(2026, 2, 18),
                            ServiceStatus = "Completed",
                            ServiceType = "Oil Change",
                            VehicleId = 7
                        },
                        new
                        {
                            MaintenanceId = 8,
                            CreatedDate = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 8,
                            Remarks = "Front brakes replaced",
                            ServiceCost = 2200.00m,
                            ServiceDate = new DateOnly(2026, 2, 22),
                            ServiceStatus = "Completed",
                            ServiceType = "Brake Inspection",
                            VehicleId = 8
                        },
                        new
                        {
                            MaintenanceId = 9,
                            CreatedDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 9,
                            Remarks = "Fuel pump replaced",
                            ServiceCost = 22000.00m,
                            ServiceDate = new DateOnly(2026, 3, 5),
                            ServiceStatus = "Completed",
                            ServiceType = "Engine Repair",
                            VehicleId = 9
                        },
                        new
                        {
                            MaintenanceId = 10,
                            CreatedDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 10,
                            Remarks = "Two rear tyres replaced",
                            ServiceCost = 6500.00m,
                            ServiceDate = new DateOnly(2026, 3, 10),
                            ServiceStatus = "Completed",
                            ServiceType = "Tyre Replacement",
                            VehicleId = 10
                        },
                        new
                        {
                            MaintenanceId = 11,
                            CreatedDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 2,
                            Remarks = "Periodic service completed",
                            ServiceCost = 4000.00m,
                            ServiceDate = new DateOnly(2026, 3, 15),
                            ServiceStatus = "Completed",
                            ServiceType = "General Service",
                            VehicleId = 1
                        },
                        new
                        {
                            MaintenanceId = 12,
                            CreatedDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 3,
                            Remarks = "Battery replaced",
                            ServiceCost = 3200.00m,
                            ServiceDate = new DateOnly(2026, 3, 20),
                            ServiceStatus = "Completed",
                            ServiceType = "Battery Check",
                            VehicleId = 2
                        },
                        new
                        {
                            MaintenanceId = 13,
                            CreatedDate = new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 4,
                            Remarks = "Oil and filter changed",
                            ServiceCost = 2600.00m,
                            ServiceDate = new DateOnly(2026, 4, 2),
                            ServiceStatus = "Completed",
                            ServiceType = "Oil Change",
                            VehicleId = 3
                        },
                        new
                        {
                            MaintenanceId = 14,
                            CreatedDate = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 5,
                            Remarks = "Brake fluid topped up",
                            ServiceCost = 1500.00m,
                            ServiceDate = new DateOnly(2026, 4, 7),
                            ServiceStatus = "Completed",
                            ServiceType = "Brake Inspection",
                            VehicleId = 4
                        },
                        new
                        {
                            MaintenanceId = 15,
                            CreatedDate = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 6,
                            Remarks = "Undergoing scheduled service",
                            ServiceCost = 3800.00m,
                            ServiceDate = new DateOnly(2026, 4, 12),
                            ServiceStatus = "InProgress",
                            ServiceType = "General Service",
                            VehicleId = 5
                        },
                        new
                        {
                            MaintenanceId = 16,
                            CreatedDate = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 7,
                            Remarks = "Coolant system repair ongoing",
                            ServiceCost = 18000.00m,
                            ServiceDate = new DateOnly(2026, 4, 18),
                            ServiceStatus = "InProgress",
                            ServiceType = "Engine Repair",
                            VehicleId = 6
                        },
                        new
                        {
                            MaintenanceId = 17,
                            CreatedDate = new DateTime(2026, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 8,
                            Remarks = "Front tyres replaced",
                            ServiceCost = 7500.00m,
                            ServiceDate = new DateOnly(2026, 4, 22),
                            ServiceStatus = "Completed",
                            ServiceType = "Tyre Replacement",
                            VehicleId = 7
                        },
                        new
                        {
                            MaintenanceId = 18,
                            CreatedDate = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 9,
                            Remarks = "High mileage oil used",
                            ServiceCost = 2700.00m,
                            ServiceDate = new DateOnly(2026, 5, 3),
                            ServiceStatus = "Completed",
                            ServiceType = "Oil Change",
                            VehicleId = 8
                        },
                        new
                        {
                            MaintenanceId = 19,
                            CreatedDate = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 10,
                            Remarks = "Battery health checked OK",
                            ServiceCost = 450.00m,
                            ServiceDate = new DateOnly(2026, 5, 8),
                            ServiceStatus = "Completed",
                            ServiceType = "Battery Check",
                            VehicleId = 9
                        },
                        new
                        {
                            MaintenanceId = 20,
                            CreatedDate = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 1,
                            Remarks = "Cancelled due to driver absence",
                            ServiceCost = 2000.00m,
                            ServiceDate = new DateOnly(2026, 5, 12),
                            ServiceStatus = "Cancelled",
                            ServiceType = "Brake Inspection",
                            VehicleId = 10
                        },
                        new
                        {
                            MaintenanceId = 21,
                            CreatedDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 3,
                            Remarks = "Rescheduled to next week",
                            ServiceCost = 4200.00m,
                            ServiceDate = new DateOnly(2026, 5, 17),
                            ServiceStatus = "Cancelled",
                            ServiceType = "General Service",
                            VehicleId = 1
                        },
                        new
                        {
                            MaintenanceId = 22,
                            CreatedDate = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 4,
                            Remarks = "Injector cleaning done",
                            ServiceCost = 12000.00m,
                            ServiceDate = new DateOnly(2026, 5, 22),
                            ServiceStatus = "Completed",
                            ServiceType = "Engine Repair",
                            VehicleId = 2
                        },
                        new
                        {
                            MaintenanceId = 23,
                            CreatedDate = new DateTime(2026, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 5,
                            Remarks = "Routine oil change",
                            ServiceCost = 2500.00m,
                            ServiceDate = new DateOnly(2026, 5, 27),
                            ServiceStatus = "Completed",
                            ServiceType = "Oil Change",
                            VehicleId = 3
                        },
                        new
                        {
                            MaintenanceId = 24,
                            CreatedDate = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 6,
                            Remarks = "All tyres replaced due to wear",
                            ServiceCost = 9000.00m,
                            ServiceDate = new DateOnly(2026, 6, 2),
                            ServiceStatus = "Completed",
                            ServiceType = "Tyre Replacement",
                            VehicleId = 4
                        },
                        new
                        {
                            MaintenanceId = 25,
                            CreatedDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 7,
                            Remarks = "Battery replaced - weak charge",
                            ServiceCost = 600.00m,
                            ServiceDate = new DateOnly(2026, 6, 5),
                            ServiceStatus = "Completed",
                            ServiceType = "Battery Check",
                            VehicleId = 5
                        },
                        new
                        {
                            MaintenanceId = 26,
                            CreatedDate = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 8,
                            Remarks = "Rear brake drum replacement",
                            ServiceCost = 1700.00m,
                            ServiceDate = new DateOnly(2026, 6, 8),
                            ServiceStatus = "InProgress",
                            ServiceType = "Brake Inspection",
                            VehicleId = 6
                        },
                        new
                        {
                            MaintenanceId = 27,
                            CreatedDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 9,
                            Remarks = "Quarterly service due",
                            ServiceCost = 3600.00m,
                            ServiceDate = new DateOnly(2026, 6, 10),
                            ServiceStatus = "Scheduled",
                            ServiceType = "General Service",
                            VehicleId = 7
                        },
                        new
                        {
                            MaintenanceId = 28,
                            CreatedDate = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 10,
                            Remarks = "Overdue oil change",
                            ServiceCost = 2900.00m,
                            ServiceDate = new DateOnly(2026, 6, 12),
                            ServiceStatus = "Scheduled",
                            ServiceType = "Oil Change",
                            VehicleId = 8
                        },
                        new
                        {
                            MaintenanceId = 29,
                            CreatedDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 1,
                            Remarks = "Major engine overhaul planned",
                            ServiceCost = 25000.00m,
                            ServiceDate = new DateOnly(2026, 6, 15),
                            ServiceStatus = "Scheduled",
                            ServiceType = "Engine Repair",
                            VehicleId = 9
                        },
                        new
                        {
                            MaintenanceId = 30,
                            CreatedDate = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 2,
                            Remarks = "New tyres before monsoon season",
                            ServiceCost = 7000.00m,
                            ServiceDate = new DateOnly(2026, 6, 18),
                            ServiceStatus = "Scheduled",
                            ServiceType = "Tyre Replacement",
                            VehicleId = 10
                        });
                });

            modelBuilder.Entity("FleetMaintenanceApi.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PurchaseYear")
                        .HasColumnType("int");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VehicleId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            Brand = "Tata",
                            IsActive = true,
                            Model = "Ace",
                            PurchaseYear = 2021,
                            VehicleNumber = "TN38AB1234",
                            VehicleType = "Truck"
                        },
                        new
                        {
                            VehicleId = 2,
                            Brand = "Ashok",
                            IsActive = true,
                            Model = "Leyland 10",
                            PurchaseYear = 2020,
                            VehicleNumber = "TN09CD5678",
                            VehicleType = "Van"
                        },
                        new
                        {
                            VehicleId = 3,
                            Brand = "Mahindra",
                            IsActive = true,
                            Model = "Blazo",
                            PurchaseYear = 2019,
                            VehicleNumber = "TN45EF9012",
                            VehicleType = "Truck"
                        },
                        new
                        {
                            VehicleId = 4,
                            Brand = "Tata",
                            IsActive = true,
                            Model = "Xenon",
                            PurchaseYear = 2022,
                            VehicleNumber = "TN22GH3456",
                            VehicleType = "Pickup"
                        },
                        new
                        {
                            VehicleId = 5,
                            Brand = "Eicher",
                            IsActive = true,
                            Model = "Pro 2049",
                            PurchaseYear = 2021,
                            VehicleNumber = "TN11IJ7890",
                            VehicleType = "Mini Truck"
                        },
                        new
                        {
                            VehicleId = 6,
                            Brand = "Force",
                            IsActive = false,
                            Model = "Traveller",
                            PurchaseYear = 2020,
                            VehicleNumber = "TN33KL2345",
                            VehicleType = "Van"
                        },
                        new
                        {
                            VehicleId = 7,
                            Brand = "BharatBenz",
                            IsActive = true,
                            Model = "1217C",
                            PurchaseYear = 2023,
                            VehicleNumber = "TN55MN6789",
                            VehicleType = "Truck"
                        },
                        new
                        {
                            VehicleId = 8,
                            Brand = "Isuzu",
                            IsActive = true,
                            Model = "D-Max",
                            PurchaseYear = 2022,
                            VehicleNumber = "TN77OP0123",
                            VehicleType = "Pickup"
                        },
                        new
                        {
                            VehicleId = 9,
                            Brand = "Tata",
                            IsActive = true,
                            Model = "407",
                            PurchaseYear = 2018,
                            VehicleNumber = "TN99QR4567",
                            VehicleType = "Mini Truck"
                        },
                        new
                        {
                            VehicleId = 10,
                            Brand = "Mahindra",
                            IsActive = true,
                            Model = "Supro",
                            PurchaseYear = 2023,
                            VehicleNumber = "TN66ST8901",
                            VehicleType = "Van"
                        });
                });

            modelBuilder.Entity("FleetMaintenanceApi.Models.MaintenanceRecord", b =>
                {
                    b.HasOne("FleetMaintenanceApi.Models.Driver", "Driver")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FleetMaintenanceApi.Models.Vehicle", "Vehicle")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("FleetMaintenanceApi.Models.Driver", b =>
                {
                    b.Navigation("MaintenanceRecords");
                });

            modelBuilder.Entity("FleetMaintenanceApi.Models.Vehicle", b =>
                {
                    b.Navigation("MaintenanceRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
